version: '2.2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "127.0.0.1:2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "127.0.0.1:9092:9092"
    environment:
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 5
      KAFKA_CREATE_TOPICS: "topic-getting-things-done:5:1"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  command-service:
    image: spring-cloud/getting-things-done/command-service
    build: ../gtd-command-service/
    mem_limit: 256m
    links:
      - discovery-service
    environment:
      SERVER_PORT: 8089
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_PROFILES_ACTIVE: configserver
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      CONFIG_SERVER_URI: http://config-server:8888
      CONFIG_SERVER_USERNAME: admin
      CONFIG_SERVER_PASSWORD: admin
  query-service:
    image: spring-cloud/getting-things-done/query-service
    build: ../gtd-query-service/
    mem_limit: 256m
    links:
      - discovery-service
    environment:
      SERVER_PORT: 8090
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
  discovery-service:
    image: spring-cloud/getting-things-done/discovery-service
    build: ../gtd-discovery-service/
    mem_limit: 256m
    ports:
      - "127.0.0.1:8761:8761"
    environment:
      eureka.instance.hostname: discovery-service
  edge-service:
    image: spring-cloud/getting-things-done/edge-service
    build: ../gtd-edge-service/
    mem_limit: 256m
    ports:
      - "127.0.0.1:8080:8080"
    links:
      - discovery-service
      - command-service
      - query-service
      - config-server
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
  config-server:
    image: spring-cloud/getting-things-done/config-server
    build: ../gtd-config-server/
    mem_limit: 256m
    ports:
      - "127.0.0.1:8888:8888"
    links:
      - discovery-service
    environment:
      SPRING_PROFILES_ACTIVE: docker,native
      ENCRYPT_KEY: my-very-secure-encrypt-key
      SPRING_SECURITY_USER_NAME: admin
      SPRING_SECURITY_USER_PASSWORD: admin
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
