spring:
  application:
    name: gtd-command-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka

---

spring.config.activate.on-profile: configserver
spring.config.import: "optional:configserver:"

spring:
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 500
        multiplier: 1.3
        max-interval: 1000
        max-attempts: 5
      username: ${CONFIG_SERVER_USERNAME}
      password: ${CONFIG_SERVER_PASSWORD}