server:
  port: 8090
  servlet:
    context-path: /
  forward-headers-strategy: framework

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gtd-query-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: spring.cloud.example.gtd.event.ItemEventDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      isolation-level: read_committed
    listener:
      ack-mode: MANUAL

gtd:
  topic: topic-getting-things-done
  groupId: getting-things-done-query

management:
  security:
    enabled: false

api:
  get-items:
    description: Returns all todo items.
    notes: Returns the list of all managed todo items. This includes closed items.
  get-item:
    description: Returns details on a given todo item.
    notes: Returns the detailed representation of the todo item that is identified by the given ID.
  response-codes:
    ok.description: OK
    notFound.description: An item with the given ID does not exist.
    internalServerError.description: The query service was unable to process the request due to an internal server error.
  common:
    version: 1.0.0
    title: Getting Things Done - Query Service API
    description: This API is used to query for items.
    license: MIT
    licenseUrl: https://opensource.org/license/mit/
    contact:
      name: Markus Günther
      url: https://www.mguenther.net
      email: mail@mguenther.net

springdoc:
  swagger-ui.path: /openapi/swagger-ui.html
  api-docs.path: /openapi/v3/api-docs
  packagesToScan: spring.cloud.example.gtd.api
  pathsToMatch: /**